# Generated by Django 5.2.17 on 2026-09-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceplan',
            name='created_by_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='equipment_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
