# Generated by Django 5.2.17 on 2026-09-15 10:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetProjection',
            fields=[
                ('asset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('process', models.CharField(blank=True, max_length=100)),
                ('factory', models.CharField(blank=True, max_length=100)),
                ('workshop', models.CharField(blank=True, max_length=100)),
                ('line', models.CharField(blank=True, max_length=100)),
                ('station', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_projections',
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('event_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_events',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wo_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Work Order Code')),
                ('equipment', models.IntegerField(db_index=True, verbose_name='Equipment')),
                ('equipment_code', models.CharField(blank=True, default='', max_length=50)),
                ('equipment_name', models.CharField(blank=True, default='', max_length=200)),
                ('wo_type', models.CharField(choices=[('PM', 'Preventive Maintenance'), ('CM', 'Corrective Maintenance'), ('inspection', 'Inspection')], default='CM', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('canceled', 'Canceled')], db_index=True, default='open', max_length=20)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('requested_by_id', models.IntegerField(db_index=True)),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('assignee_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('assignee_name', models.CharField(blank=True, default='', max_length=100)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by_id', models.IntegerField(blank=True, null=True)),
                ('maintenance_plan_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('downtime_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_by_id', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_id', models.IntegerField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'db_table': 'work_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment', 'status'], name='work_orders_equipme_ed75e4_idx'), models.Index(fields=['status', 'created_at'], name='work_orders_status_2af962_idx'), models.Index(fields=['wo_type', 'status'], name='work_orders_wo_type_c4ad5e_idx'), models.Index(fields=['assignee_id', 'status'], name='work_orders_assigne_f50155_idx'), models.Index(fields=['priority', 'status'], name='work_orders_priorit_72b397_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_id', models.IntegerField(db_index=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=100)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workorders_api.workorder')),
            ],
            options={
                'db_table': 'work_order_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part_code', models.CharField(max_length=50)),
                ('part_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='workorders_api.workorder')),
            ],
            options={
                'db_table': 'work_order_parts',
                'ordering': ['part_code'],
            },
        ),
    ]
