# Generated by Django 5.2.17 on 2026-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetProjection',
            fields=[
                ('asset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('process', models.CharField(blank=True, max_length=100)),
                ('factory', models.CharField(blank=True, max_length=100)),
                ('workshop', models.CharField(blank=True, max_length=100)),
                ('line', models.CharField(blank=True, max_length=100)),
                ('station', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inspection_asset_projections',
            },
        ),
        migrations.CreateModel(
            name='InspectionRoute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('route_items', models.JSONField()),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('inspector_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('inspector_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inspection_routes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('items_template', models.JSONField()),
                ('equipment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inspection_templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inspection_processed_events',
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('equipment', models.IntegerField(db_index=True)),
                ('equipment_code', models.CharField(blank=True, max_length=100)),
                ('equipment_name', models.CharField(blank=True, max_length=200)),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('items', models.JSONField()),
                ('inspector_id', models.IntegerField(db_index=True)),
                ('inspector_name', models.CharField(blank=True, max_length=150)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning')], default='pass', max_length=20)),
                ('triggered_work_order_id', models.IntegerField(blank=True, null=True)),
                ('work_order_request_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'inspection_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment', 'created_at'], name='inspection__equipme_a1f9e1_idx'), models.Index(fields=['inspector_id', 'created_at'], name='inspection__inspect_0a0663_idx'), models.Index(fields=['result', 'created_at'], name='inspection__result_43a83c_idx')],
            },
        ),
    ]
