from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetProjection',
            fields=[
                ('asset_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={'ordering': ['asset_code']},
        ),
        migrations.CreateModel(
            name='WorkOrderFact',
            fields=[
                ('work_order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('wo_code', models.CharField(max_length=50)),
                ('asset_id', models.BigIntegerField()),
                ('asset_code', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=200, null=True)),
                ('wo_type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('priority', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('assignee_id', models.BigIntegerField(blank=True, null=True)),
                ('assignee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('maintenance_plan_id', models.BigIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('downtime_minutes', models.IntegerField(blank=True, null=True)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField()),
            ],
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.CreateModel(
            name='PartConsumptionFact',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('part_id', models.BigIntegerField()),
                ('part_code', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('work_order_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_id', models.BigIntegerField()),
                ('occurred_at', models.DateTimeField()),
            ],
            options={'ordering': ['-occurred_at']},
        ),
        migrations.CreateModel(
            name='InspectionFact',
            fields=[
                ('inspection_record_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('asset_id', models.BigIntegerField()),
                ('work_order_id', models.BigIntegerField(blank=True, null=True)),
                ('inspector_id', models.BigIntegerField()),
                ('failed_items', models.JSONField(default=list)),
                ('failed_item_count', models.IntegerField(default=0)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={'ordering': ['-occurred_at']},
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('workorder_summary', 'Work Order Summary'), ('downtime_analysis', 'Downtime Analysis'), ('spareparts_usage', 'Spare Parts Usage'), ('maintenance-compliance', 'Maintenance Compliance'), ('cost-analysis', 'Cost Analysis'), ('technician-performance', 'Technician Performance'), ('equipment-availability', 'Equipment Availability')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField()),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'scheduled_reports', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('output_file', models.CharField(blank=True, max_length=255, null=True)),
                ('output_format', models.CharField(blank=True, max_length=10, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('requested_by_id', models.BigIntegerField(blank=True, null=True)),
                ('requested_by_name', models.CharField(blank=True, max_length=150)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='analytics.scheduledreport')),
            ],
            options={'db_table': 'report_runs', 'ordering': ['-created_at']},
        ),
        migrations.AddIndex(model_name='workorderfact', index=models.Index(fields=['status', 'created_at'], name='analytics_w_status_5ecdb0_idx')),
        migrations.AddIndex(model_name='workorderfact', index=models.Index(fields=['wo_type', 'created_at'], name='analytics_w_wo_type_08d1aa_idx')),
        migrations.AddIndex(model_name='workorderfact', index=models.Index(fields=['asset_id', 'created_at'], name='analytics_w_asset_i_a50a11_idx')),
        migrations.AddIndex(model_name='workorderfact', index=models.Index(fields=['assignee_id', 'created_at'], name='analytics_w_assigne_b45fbd_idx')),
        migrations.AddIndex(model_name='partconsumptionfact', index=models.Index(fields=['part_id', 'occurred_at'], name='analytics_p_part_id_3ffa6d_idx')),
        migrations.AddIndex(model_name='partconsumptionfact', index=models.Index(fields=['work_order_id', 'occurred_at'], name='analytics_p_work_or_840217_idx')),
        migrations.AddIndex(model_name='inspectionfact', index=models.Index(fields=['asset_id', 'occurred_at'], name='analytics_i_asset_i_3ee4b6_idx')),
        migrations.AddIndex(model_name='reportrun', index=models.Index(fields=['report_type', 'created_at'], name='report_runs_report__a2eddc_idx')),
        migrations.AddIndex(model_name='reportrun', index=models.Index(fields=['status', 'created_at'], name='report_runs_status_56b995_idx')),
    ]
